[package]
name = "md_to_html"
version = "0.1.0"
authors = ["buchiyexiao <1091404874@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
comrak = "0.8.0"